name: nanopore_qc_env
channels:
  - conda-forge
  - bioconda
dependencies:
  - pandas
  - snakemake-minimal >=5.24.1
  - jinja2 =2.11
  - networkx =2.5
  - filtlong
  - nanoplot
  - porechop
  - coreutils
